@startuml

package Sampler {
    package "SamplerView" {}
    package "SamplerViewModel" {}
    package "SamplerModel" {}

    SamplerView ..> SamplerViewModel
    SamplerViewModel ..> SamplerModel
}

package StepSequencer {
    package "StepSequencerView" {}
    package "StepSequencerViewModel" {}
    package "StepSequencerModel" {}

    StepSequencerView ..> StepSequencerViewModel
    StepSequencerViewModel ..> StepSequencerModel
}

package Infrastructure {}
package AudioServiceLayer Facade {}

SamplerViewModel ..> AudioServiceLayer
StepSequencerViewModel ..> AudioServiceLayer
SamplerViewModel ..> Infrastructure

note bottom of AudioServiceLayer : Facade over AVFoundation

@enduml
