sequenceDiagram
    autonumber
    actor User
    participant View as StepSequencerView
    participant VM as StepSequencerViewModel
    participant URM as UndoRedoManager
    participant Cmd as ToggleStepCommand
    participant Engine as MusicEngine

        note right of User: UNDO ACTION
        User->>View: Taps Undo Button
        View->>VM: undo()
        activate VM
        VM->>URM: undo()
        activate URM
        
        URM->>URM: pop from undoStack
        URM->>Cmd: undo()
        activate Cmd
        Cmd->>VM: mutateStep(trackId, stepIndex)
        
        VM->>VM: Toggle boolean back in model
        VM->>VM: publishSnapshot()
        VM->>Engine: apply(snapshot: SequencerSnapshot)
        
        URM->>URM: push to redoStack
        deactivate Cmd
        deactivate URM
        deactivate VM
    
    
        note right of User: REDO ACTION
        User->>View: Taps Redo Button
        View->>VM: redo()
        activate VM
        VM->>URM: redo()
        activate URM
        
        URM->>URM: pop from redoStack
        URM->>Cmd: execute()
        activate Cmd
        Cmd->>VM: mutateStep(trackId, stepIndex)
        
        VM->>VM: Toggle boolean forward in model
        VM->>VM: publishSnapshot()
        VM->>Engine: apply(snapshot: SequencerSnapshot)
        
        URM->>URM: push to undoStack
        deactivate Cmd
        deactivate URM
        deactivate VM
